version: "3.2"

services:
  crawler:
    build: .
    environment:
      - SEARCH_TYPE=${SEARCH_TYPE}
      - DOWN_PATH=${DOWN_PATH}
      - EH_COOKIE=${EH_COOKIE}
      - EH_TAG=${EH_TAG}
      - EH_SOURCE=${EH_SOURCE} # 1:eh 2:exh
      - EH_DOWN_NUM=${EH_DOWN_NUM}
      - REDIS_URL=${REDIS_URL}
      - PROXY_POOL_ADDR=${PROXY_POOL_ADDR}
      - PROCESS_NUM=${PROCESS_NUM}
      - CLIENT_TIMEOUT=${CLIENT_TIMEOUT}
      - ALLOWED_FAILED_PERCENT=${ALLOWED_FAILED_PERCENT}
      - MAX_RETRY=${MAX_RETRY}
      - ENABLE_QBT_TORRENT=${ENABLE_QBT_TORRENT}
      - QBT_HOST=${QBT_HOST}
      - QBT_PORT=${QBT_PORT} 
      - QBT_USERNAME=${QBT_USERNAME}
      - QBT_PWD=${QBT_PWD}
      - QBT_CATEGORY=${QBT_CATEGORY}
      - EH_TEST_URL=${EH_TEST_URL}
      - ENABLE_ARIA_TORRENT=${ENABLE_ARIA_TORRENT}
      - ARIA_RPC_ADDRESS=${ARIA_RPC_ADDRESS}
      - ARIA_RPC_SECRET=${ARIA_RPC_SECRET}
      - ARIA_DOWN_DIR=${ARIA_DOWN_DIR}
    volumes:
      - ${DOWN_PATH}:/download
      - ${ARIA_DOWN_DIR}:/download_bt